apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kust-prod

resources:
- ../../base
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
- path: route-patch.yaml

configurations:
- namespace.yaml
