apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kust-prod

resources:
- ../../base
patches:
- deployment-patch.yaml
- service-patch.yaml
- route-patch.yaml

configurations:
- namespace.yaml
